### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [PowellDean/Locale-Codes-Country#5]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that this distribution will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining this distribution, you can have this distribution moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by PowellDean** [comment]
Hi:

Thank you for your email. I can't imagine anyone actually using this
module, but I can move it over to the zef ecosystem when I get time. I
haven't updated it in a while, and I have no tests but I can certainly add
some. Alas, the current chaos in IT caused by Broadcom's purchase of VMware
is drawing much of my attention these days.

I'm fine with continuing to maintain the module. I'll become familiar with
zef and load it there, but it will not be immediate.

Thank you for the notification. You may close this issue if you like.

Regards,
Dean Powell
Edmonton, Canada

**Comment by lizmat** [comment]
Thanks for your reply.

> I'm fine with continuing to maintain the module. I'll become familiar with
zef and load it there, but it will not be immediate.

That's fine.  I just wanted to make sure you know that *if* you'd do any updates, they will remain invisible to the ecosystem unless you'd upload them to zef.  Until then, your module will remain available and visible in its current state.
